params:  
  seed: 322
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: actor_critic
    separate: False
    space: 
      discrete:

    mlp:
      type: mlp
      activation: elu
      initializer:
        name: default
      regularizer:
        name: None
      units:
        - 128
        - 64
      
    mlp:
      units: [512]
      activation: elu
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237

  config:
    name: PongNoFrameskip_ray
    env_name: rlgpu
    score_to_win: 20.0
    normalize_value: True
    normalize_input: True
    reward_shaper:
      min_val: -1
      max_val: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    grad_norm: 1.0
    entropy_coef: 0.01
    truncate_grads: True
    learning_rate: 3e-4
    lr_schedule: adaptive
    kl_threshold: 0.01
    grad_norm: 1.0
    entropy_coef: 0.01
    truncate_grads: True
    e_clip: 0.2
    clip_value: False
    num_actors: 64
    horizon_length: 128
    minibatch_size: 2048
    mini_epochs: 4
    critic_coef: 2
    max_epochs: 500
    use_diagnostics: False

    env_config:
      env_name: rlgpu

    player:
      render: True
      games_num: 100
      n_game_life: 1
      deterministic: True